### ISSUE TITLE
手势 复制了示例代码 没有效果

### ISSUE THREAD

**Issue by 2788** [tarojsx/library#1]

**Comment by cncolder** [comment]
@2788 这里的 react-spring 是以研究为目的, 实际效果受限于小程序 setData 性能.

react-spring 的原理是动态修改组件 style, 在 web 上这种作法可以跳过 react, 因此动画平滑.
可是在 taro 里, 动态修改 style 会强制 update, 进而以每秒60次的速度 setData.

所以不建议用在真实项目中.

另外你要支持手势, 必须填平小程序触摸事件和 DOM 事件之间的差异才行.
