### ISSUE TITLE
请问一下这个怎么解决

### ISSUE THREAD

**Issue by eruca** [tarojsx/library#3]
```js
import React, { CSSProperties } from "react";
import { F2 } from "@tarojsx/library/dist/antv";

export interface LineInputType {
    date: string;
    value: number;
}

interface ILine {
    data: LineInputType[];
    style?: CSSProperties;
}

export default function Line({
    data = [],
    style = { width: "100vw", height: "50vh" },
}: ILine) {
    return (
        <F2 style={style} data={data}>
            {({ chart, data }) => {
                chart.source(data, {
                    date: {
                        type: "timeCat",
                        range: [0, 1],
                        tickCount: 3,
                    },
                    value: {
                        tickCount: 5,
                    },
                });

                chart.tooltip({
                    custom: true,
                    showXTip: true,
                    showYTip: true,
                    snap: true,
                    crosshairsType: "xy",
                    crosshairsStyle: {
                        lineDash: [2],
                    },
                });

                chart.axis("date", {
                    label: function label(text, index, total) {
                        const textCfg: any = {};
                        if (index === 0) {
                            textCfg.textAlign = "left";
                        } else if (index === total - 1) {
                            textCfg.textAlign = "right";
                        }
                        return textCfg;
                    },
                });

                chart.line().position("date*value");
                chart.render();
            }}
        </F2>
    );
}

```

调用其实
```jsx
      <View>
            <Line data={data} />
            <View>
                <Picker
                    mode="selector"
                    range={selectors}
                    value={currIndex}
                    onChange={(e) =>
                        setCurrIndex(
                            typeof e.detail.value === "number"
                                ? e.detail.value
                                : parseInt(e.detail.value, 10)
                        )
                    }
                >
                    <AtList>
                        <AtListItem
                            title="请选择展示内容"
                            extraText={selectors[currIndex]}
                        />
                    </AtList>
                </Picker>
            </View>
        </View>
```

document.createElement(...).getContext is not a function
TypeError: document.createElement(...).getContext is not a function
    at measureText (http://127.0.0.1:27232/appservice/pages/records/graph/index.js:873:48)
    at Text._getTextWidth (http://127.0.0.1:27232/appservice/pages/records/graph/index.js:9252:19)
    at Text.calculateBox (http://127.0.0.1:27232/appservice/pages/records/graph/index.js:9172:26)
    at Text.getBBox (http://127.0.0.1:27232/appservice/pages/records/graph/index.js:7585:23)
    at TextBox._getBBox (http://127.0.0.1:27232/appservice/pages/records/graph/index.js:13878:34)
    at TextBox.updateContent (http://127.0.0.1:27232/appservice/pages/records/graph/index.js:13905:37)
    at new TextBox (http://127.0.0.1:27232/appservice/pages/records/graph/index.js:13833:16)
    at new Tooltip (http://127.0.0.1:27232/appservice/pages/records/graph/index.js:14076:25)
    at TooltipController.render (http://127.0.0.1:27232/appservice/pages/records/graph/index.js:14711:23)
    at Object.afterGeomDraw (http://127.0.0.1:27232/appservice/pages/records/graph/index.js:15061:25)

**Comment by cncolder** [comment]
@eruca 研究了一下, 是 F2 本身的问题. https://github.com/antvis/F2/issues/1015

下面这两个属性, F2 会尝试计算文字的宽高, 计算过程要用到 canvas context, 但不知什么原因, 传递的过程中丢失了, 导致为了计算文字宽高, F2 会尝试新建一个 canvas, `document.createElement('canvas').getContext('2d')`, 所以你会看到上面的错误: `document.createElement(...).getContext is not a function`.

```js
chart.tooltip({
  showXTip: true,
  showYTip: true,
})
```

**Comment by eruca** [comment]
有解决办法吗？

**Comment by cncolder** [comment]
@eruca 意思就是, 要么 F2 修复这个 BUG, 要么不用 showXTip.
小程序里无法模拟出同步的 `document.createElement('canvas').getContext('2d')`

**Comment by eruca** [comment]
你可以参考一下taro-f2这个包，它也是用原生f2包de

**Comment by cncolder** [comment]
F2 那边已经在修复这个问题了. https://github.com/antvis/F2/pull/1017

taro-f2 采用给 `F2.Util.measureText` 打补丁的方式, 新版本 F2 这个方法是私有的.

**Comment by eruca** [comment]
谢谢
